import type { SettingsLocaleTable } from "../types";

/** Brazilian Portuguese overrides for the files tab. */
export const files: SettingsLocaleTable = {
	tabs: { files: "Arquivos" },
	groups: {
		files: {
			Editing: "Edição",
			Reading: "Leitura",
			"Read Summaries": "Resumos de Leitura",
			LSP: "LSP",
		},
	},
	paths: {
		"edit.mode": {
			label: "Modo de Edição",
			description: "Escolhe a variante da ferramenta de edição (replace, patch, hashline ou apply_patch)",
		},
		"edit.fuzzyMatch": {
			label: "Correspondência Aproximada",
			description: "Aceita correspondências aproximadas de alta confiança para diferenças de espaços em branco",
		},
		"edit.fuzzyThreshold": {
			label: "Limite da Correspondência Aproximada",
			description: "Limite de similaridade (0-1) para aceitar correspondências aproximadas",
		},
		"edit.streamingAbort": {
			label: "Abortar Quando a Prévia Falhar",
			description: "Aborta as chamadas da ferramenta de edição em stream quando a prévia do patch falha",
		},
		"edit.recoverInlineEdits": {
			label: "Recuperar Edições Enviadas no Texto",
			description:
				"Executa as edições que o modelo emite como texto puro, convertendo-as em chamadas da ferramenta de edição",
		},
		"edit.blockAutoGenerated": {
			label: "Bloquear Arquivos Gerados Automaticamente",
			description: "Impede a edição de arquivos que parecem gerados automaticamente (protoc, sqlc, swagger etc.)",
		},
		"edit.enforceSeenLines": {
			label: "Exigir Linhas Já Vistas",
			description: "Rejeita edições ancoradas em linhas que uma leitura/busca anterior nunca exibiu por completo",
		},
		"edit.blackbox.enabled": {
			label: "Registrar Regressões de Parse",
			description: "Anexa o código-fonte completo antes/depois quando uma edição introduz falha de parse da AST",
		},
		"edit.autoRepair.enabled": {
			label: "Corrigir Regressões de Parse Automaticamente",
			description:
				"Quando uma edição quebra o parse da AST do arquivo, pede ao modelo smol para corrigir a região quebrada (validado por novo parse; na falha, apenas avisa)",
		},
		readLineNumbers: {
			label: "Números de Linha",
			description: "Prefixa números de linha na saída da ferramenta de leitura por padrão",
		},
		"read.defaultLimit": {
			label: "Limite Padrão de Leitura",
			description: "Número padrão de linhas retornadas quando o agente chama read sem um limite",
		},
		"read.renderMarkdown": {
			label: "Prévias de Markdown",
			description:
				"Renderiza resultados de leitura de Markdown como prévias formatadas no terminal, em vez do código-fonte bruto",
		},
		"read.summarize.enabled": {
			label: "Resumos de Leitura",
			description: "Retorna resumos estruturais do código quando read é chamado sem um seletor explícito",
		},
		"read.summarize.prose": {
			label: "Resumos de Prosa",
			description: "Retorna resumos estruturais nas leituras de Markdown e de texto puro",
		},
		"read.summarize.minBodyLines": {
			label: "Linhas de Corpo no Resumo de Leitura",
			description: "Tamanho mínimo de um corpo ou literal multilinha para o resumo de leitura recolhê-lo",
		},
		"read.summarize.minCommentLines": {
			label: "Linhas de Comentário no Resumo de Leitura",
			description: "Tamanho mínimo de um comentário em bloco multilinha para o resumo de leitura recolhê-lo",
		},
		"read.summarize.minTotalLines": {
			label: "Tamanho Mínimo de Arquivo para Resumo de Leitura",
			description: "Arquivos com menos linhas no total são lidos na íntegra, em vez de resumidos estruturalmente",
		},
		"read.summarize.unfoldUntil": {
			label: "Meta de Expansão do Resumo de Leitura",
			description:
				"Expande trechos elidíveis em BFS até o resumo ter ao menos esta quantidade de linhas visíveis. 0 mantém apenas as elisões mais externas.",
		},
		"read.summarize.unfoldLimit": {
			label: "Teto de Expansão do Resumo de Leitura",
			description:
				"Teto rígido para o tamanho do resumo durante a expansão em BFS. Uma expansão cujas linhas reveladas passariam desse teto é ignorada (esse trecho fica recolhido) e a expansão continua com os trechos restantes.",
		},
		"read.toolResultPreview": {
			label: "Prévias de Leitura Inline",
			description:
				"Renderiza os resultados da ferramenta de leitura inline na transcrição, em vez de linhas de resumo",
		},
		"lsp.enabled": {
			label: "LSP",
			description:
				"Ativa a ferramenta lsp para inteligência de código (definições, referências, diagnósticos, renomear)",
		},
		"lsp.lazy": {
			label: "Inicialização Preguiçosa do LSP",
			description:
				"Inicia os language servers no primeiro uso (ferramenta lsp ou edição de um tipo de arquivo compatível), em vez de na abertura da sessão",
		},
		"lsp.shared": {
			label: "Language Servers Compartilhados",
			description:
				"Compartilha um language server por projeto entre instâncias do omp via o broker do daemon (recorre a servidores privados quando indisponível)",
		},
		"lsp.formatOnWrite": {
			label: "Formatar ao Escrever",
			description: "Formata automaticamente os arquivos de código via LSP depois de escrever",
		},
		"lsp.diagnosticsOnWrite": {
			label: "Diagnósticos ao Escrever",
			description: "Retorna diagnósticos do LSP depois de escrever arquivos de código",
		},
		"lsp.diagnosticsOnEdit": {
			label: "Diagnósticos ao Editar",
			description: "Retorna diagnósticos do LSP depois de editar arquivos de código",
		},
		"lsp.diagnosticsDeduplicate": {
			label: "Deduplicar Diagnósticos",
			description:
				"Suprime diagnósticos do LSP pós-edição já mostrados para um arquivo; exibe apenas os novos ou alterados",
		},
	},
	options: {
		"edit.fuzzyThreshold": {
			"0.85": { label: "0.85", description: "Tolerante" },
			"0.90": { label: "0.90", description: "Moderado" },
			"0.95": { label: "0.95", description: "Padrão" },
			"0.98": { label: "0.98", description: "Estrito" },
		},
		"read.defaultLimit": {
			"200": { label: "200 linhas" },
			"300": { label: "300 linhas" },
			"500": { label: "500 linhas" },
			"1000": { label: "1000 linhas" },
			"5000": { label: "5000 linhas" },
		},
	},
};
